// Mocks generated by Mockito 5.4.5 from annotations
// in mywallet_mobile/test/features/authentification/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:mywallet_mobile/core/custom_barrel.dart' as _i3;
import 'package:mywallet_mobile/features/authentification/data/data_sources/auth_local_data_source.dart'
    as _i5;
import 'package:mywallet_mobile/features/authentification/data/data_sources/auth_remote_data_source.dart'
    as _i8;
import 'package:mywallet_mobile/features/authentification/data/model/token_model.dart'
    as _i6;
import 'package:mywallet_mobile/features/authentification/data/model/user_model.dart'
    as _i2;
import 'package:mywallet_mobile/features/authentification/domain/entities/user_signup.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i5.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheToken(_i6.TokenModel? token) =>
      (super.noSuchMethod(
            Invocation.method(#cacheToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getAccessToken, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getRefreshToken, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> cacheUser(_i2.UserModel? userData) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [userData]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserModel> getCacheUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheUser, []),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#getCacheUser, [])),
            ),
          )
          as _i4.Future<_i2.UserModel>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i8.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> signup(_i9.UserSignup? userData) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [userData]),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#signup, [userData])),
            ),
          )
          as _i4.Future<_i2.UserModel>);
}
